# Generated by Django 2.0.13 on 2023-06-17 08:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0035_auto_20210824_0933'),
        ('hr', '0063_auto_20211122_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Job Skill Activity Amount')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_amounts', to='hr.Job', verbose_name='Job')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_amounts', to='skills.WorkType', verbose_name='Skill activity')),
            ],
            options={
                'verbose_name': 'Job Skill Activity Amount',
                'verbose_name_plural': 'Job Skill Activity Amounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobamount',
            unique_together={('job', 'worktype')},
        ),
    ]
