# Generated by Django 2.0.13 on 2023-06-22 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0064_create_job_amount_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='manager_who_approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_approved_time_sheets', to='core.CompanyContact', verbose_name='Manager who approved'),
        ),
    ]
