# Generated by Django 2.0.13 on 2023-07-13 20:39

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_auto_20221221_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='phone_fax',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
