# Generated by Django 2.0.13 on 2023-07-14 05:52

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_auto_20230714_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerule',
            name='separation_rule',
            field=models.CharField(choices=[('one_invoice', 'One invoice'), ('per_jobsite', 'Per jobsite'), ('per_candidate', 'Per candidate')], default='one_invoice', max_length=13, verbose_name='Separation rule'),
        ),
    ]
