# Generated by Django 2.0.13 on 2023-07-19 11:56

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_auto_20230714_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='skill_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Skill Activity'),
        ),
    ]
